const labels: Record<string, string> = {
  Catalog: "Каталог",
  Lookbook: "Лукбук",
  About: "О проекте",
  Favorites: "Избранное",
  "Back to market": "← Вернуться в каталог",
  "Private list": "Личный список",
  "saved locally": "сохранено в браузере",
  "Objects for after dark.": "Объекты после наступления темноты.",
  Wearables: "Одежда",
  Objects: "Объекты",
  Scent: "Ароматы",
  Prints: "Принты",
  Digital: "Цифровые материалы",
  limited: "ограниченный выпуск",
  new: "новинка",
  digital: "цифровой материал",
  "One size": "Единый размер",
  "All objects": "Все объекты",
  "All styles": "Все стили",
  "All themes": "Все темы",
  "All sizes": "Все размеры",
  "Any price": "Любая цена",
  "Under 3 000 ₽": "До 3 000 ₽",
  "3 000–6 000 ₽": "3 000–6 000 ₽",
  "Over 6 000 ₽": "От 6 000 ₽",
  "Sort by": "Сортировка",
  "Curated match": "По подборке",
  "Most popular": "Сначала популярные",
  Featured: "Рекомендуемые",
  Newest: "Сначала новые",
  "Price: low": "Сначала дешевле",
  "Price: high": "Сначала дороже",
};

export const ru = (value: string) => labels[value] || value;

