import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowLeft, ArrowUpRight, Eye, Heart, Share2, X, ZoomIn } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";
import ProgressiveImage from "@/components/ProgressiveImage";
import Lightbox from "@/components/Lightbox";
import { favoriteProductId, readFavoriteIds, writeFavoriteIds } from "@/lib/favorites";
import { readCart, upsertCartLine, writeCart } from "@/lib/cart";

// Style reminder: Lookbook extends Occult Luxury Editorial with asymmetric spreads,
// archival captions, orange commerce signals, and fast object discovery in-place.
const assets = { hero: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663894363217/XgTNBfpPRvrnTFPr.jpg", category: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663894363217/lCrSqnLAXFKXmWXd.jpg", raven: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663894363217/RCOUOqqGlNukXVjv.jpg", nocturne: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663894363217/lJJsOdgSMDOjJmdQ.jpg", mark: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663894363217/FcXuAAsdOxmisWCl.png" };
type Look = { number: string; title: string; note: string; image: string; gallery?: string[]; products: string; quickTitle: string; quickCopy: string; price: number };
const looks: Look[] = [
  { number: "01", title: "The threshold", note: "A silhouette for rooms that keep their own hours.", image: assets.raven, gallery: [assets.raven, assets.hero], products: "Raven Hour / Acid Moon", quickTitle: "Raven Hour", quickCopy: "Heavy matte cotton, hidden satin lining, and an architectural hood.", price: 8800 },
  { number: "02", title: "Low flame", note: "Objects that make the air feel considered.", image: assets.category, gallery: [assets.category, assets.nocturne], products: "Black Fig / Ember Ritual", quickTitle: "Black Fig", quickCopy: "A low flame with a fruit-dark finish: fig, clove leaf and wet stone.", price: 2400 },
  { number: "03", title: "A quiet witness", note: "Leave one beautiful thing where it can watch.", image: assets.nocturne, gallery: [assets.nocturne, assets.raven], products: "Nocturne / The Last Séance", quickTitle: "Nocturne", quickCopy: "Hand-finished black ceramic with a soft cotton tie and a quiet point of view.", price: 5600 },
];
const addToLocalCart = (look: Look) => {
  const product = { id: look.quickTitle.toLowerCase().replaceAll(" ", "-"), title: look.quickTitle, slug: look.quickTitle.toLowerCase().replaceAll(" ", "-"), category: "Lookbook", price: look.price, shortDescription: look.quickCopy, description: look.quickCopy, tags: ["lookbook"], image: look.image, colors: ["#17151b"], stock: 8, featured: false, badge: "lookbook" };
  const current = readCart<typeof product>();
  const result = upsertCartLine(current, product);
  if (result.capped) { toast.error(`${look.quickTitle} достиг лимита доступного остатка`); return; }
  writeCart(result.lines);
  toast.success(`${look.quickTitle} добавлен в корзину`, { description: "Можно продолжить смотреть Lookbook." });
};

export default function Lookbook() {
  const [quickView, setQuickView] = useState<Look | null>(null);
  const [saved, setSaved] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("night-market-lookbook-saved") || "[]"); } catch { return []; } });
  const [favoriteIds, setFavoriteIds] = useState<string[]>(() => readFavoriteIds());
  const [lightbox, setLightbox] = useState<{ src: string; alt: string; title: string; images?: { src: string; alt: string; title?: string }[] } | null>(null);
  useEffect(() => { writeFavoriteIds(favoriteIds); }, [favoriteIds]);
  useEffect(() => { const sync = (event: Event) => setFavoriteIds((event as CustomEvent<string[]>).detail || readFavoriteIds()); window.addEventListener("night-market-favorites", sync); return () => window.removeEventListener("night-market-favorites", sync); }, []);
  useEffect(() => { const shared = new URLSearchParams(window.location.search).get("look"); const match = shared ? looks.find((look) => look.number === shared) : undefined; if (match) setQuickView(match); const onEscape = (event: KeyboardEvent) => { if (event.key === "Escape") setQuickView(null); }; window.addEventListener("keydown", onEscape); return () => window.removeEventListener("keydown", onEscape); }, []);
  const saveLook = (look: Look) => { const next = saved.includes(look.number) ? saved.filter((id) => id !== look.number) : [...saved, look.number]; setSaved(next); localStorage.setItem("night-market-lookbook-saved", JSON.stringify(next)); toast.success(next.includes(look.number) ? "Образ сохранён" : "Образ удалён из избранного"); };
  const toggleFavorite = (look: Look) => { const id = favoriteProductId(look.quickTitle); setFavoriteIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); toast.success(favoriteIds.includes(id) ? "Товар удалён из избранного" : "Товар сохранён в избранное"); };
  const shareLook = async (look: Look) => { const url = `${window.location.origin}/lookbook?look=${look.number}`; try { if (navigator.share) await navigator.share({ title: `NIGHT MARKET — ${look.title}`, text: look.note, url }); else { await navigator.clipboard.writeText(url); toast.success("Ссылка скопирована", { description: url }); } } catch { await navigator.clipboard?.writeText(url); toast.success("Ссылка скопирована", { description: url }); } };
  return <div className="nm-site nm-lookbook"><header className="nm-header"><Link className="nm-brand" href="/" aria-label="NIGHT MARKET — на главную"><ProgressiveImage src={assets.mark} alt="" /><span>NIGHT<br /><em>MARKET</em></span></Link><nav className="nm-nav" aria-label="Основная навигация"><Link href="/">Каталог</Link><a href="#looks">Коллекции</a><a href="#editorial-note">О проекте</a></nav><div className="nm-header-actions"><Link className="nm-text-button nm-favorites-button" href="/favorites" aria-label={`Избранное, ${favoriteIds.length} товаров`}><Heart size={16} /> Избранное <b>{String(favoriteIds.length).padStart(2, "0")}</b></Link><Link className="nm-text-button" href="/">← Вернуться в каталог</Link></div></header><main>
    <section className="nm-look-hero"><div><p className="nm-kicker"><span className="nm-dot" /> Лукбук / выпуск 04</p><h1>Сделайте<br /><i>комнату</i> странной.</h1><p className="nm-hero-lede">Три композиции для часов после очевидного. Объекты, текстура и силуэт в более тихом регистре.</p><a className="nm-cta" href="#looks">Открыть лукбук <ArrowDownRight size={18} /></a></div><div className="nm-look-hero-image"><button className="nm-look-hero-zoom" onClick={() => setLightbox({ src: assets.hero, alt: "A glowing obsidian talisman in a dark editorial setting", title: "NIGHT MARKET / Issue 04", images: [assets.hero, assets.raven].map((src) => ({ src, alt: "NIGHT MARKET / Issue 04", title: "NIGHT MARKET / Issue 04" })) })} aria-label="Увеличить изображение Lookbook"><ProgressiveImage src={assets.hero} alt="A glowing obsidian talisman in a dark editorial setting" /><ZoomIn size={18} /></button><span>NM / 04<br /><b>ПОЛЕВЫЕ ЗАМЕТКИ</b></span></div></section>
    <section id="looks" className="nm-look-list">{looks.map((look, index) => <article className={`nm-look ${index % 2 ? "nm-look-reverse" : ""}`} key={look.number}><div className="nm-look-image"><button className="nm-look-image-zoom" onClick={() => setLightbox({ src: look.image, alt: `${look.title} editorial arrangement`, title: look.title, images: (look.gallery ?? [look.image]).map((src) => ({ src, alt: `${look.title} editorial arrangement`, title: look.title })) })} aria-label={`Увеличить изображение ${look.title}`}><ProgressiveImage src={look.image} alt={`${look.title} editorial arrangement`} /><ZoomIn size={18} /></button><button className={`nm-look-favorite ${favoriteIds.includes(favoriteProductId(look.quickTitle)) ? "is-active" : ""}`} onClick={() => toggleFavorite(look)} aria-pressed={favoriteIds.includes(favoriteProductId(look.quickTitle))} aria-label={favoriteIds.includes(favoriteProductId(look.quickTitle)) ? `Удалить ${look.quickTitle} из избранного` : `Добавить ${look.quickTitle} в избранное`}><Heart size={15} fill={favoriteIds.includes(favoriteProductId(look.quickTitle)) ? "currentColor" : "none"} /></button><span>{look.number} / 03</span><button className="nm-look-quick" onFocus={() => setQuickView(look)} onClick={() => setQuickView(look)} aria-label={`Быстрый просмотр ${look.quickTitle}`}><Eye size={15} /> Быстрый просмотр</button></div><div className="nm-look-copy"><p className="nm-eyebrow">{look.products}</p><h2>{look.title}</h2><p>{look.note}</p><button className="nm-underlink" onClick={() => setQuickView(look)}>Быстрый просмотр <Eye size={15} /></button></div></article>)}</section>
    <section id="editorial-note" className="nm-look-note"><ProgressiveImage src={assets.mark} alt="" /><div><p className="nm-eyebrow">Заметка из архива</p><h2>Хорошая атмосфера<br /><i>работает.</i></h2><p>Каждый образ строится вокруг одного главного объекта, а текстура и тень делают остальное. Здесь нет лишних деталей. Если вещь меняет комнату — ей здесь место.</p><Link className="nm-underlink" href="/">Вернуться в каталог <ArrowLeft size={15} /></Link></div></section>
  </main><footer className="nm-footer"><Link className="nm-brand" href="/"><ProgressiveImage src={assets.mark} alt="" /><span>NIGHT<br /><em>MARKET</em></span></Link><p>Объекты после наступления темноты.</p><div><Link href="/">Каталог</Link><a href="#looks">Лукбук</a><Link href="/policies">Доставка и условия</Link><a href="https://t.me/eloquncy" target="_blank" rel="noreferrer">Telegram @eloquncy <ArrowUpRight size={14} /></a></div><small>© 2026 NIGHT MARKET. Связь через Telegram.</small></footer><div className="nm-noise" aria-hidden="true" />{quickView && <div className="nm-quick-overlay" onClick={() => setQuickView(null)}><aside className="nm-quick-view" onClick={(event) => event.stopPropagation()} role="dialog" aria-modal="true" aria-label={`Быстрый просмотр ${quickView.quickTitle}`}><button className="nm-close" onClick={() => setQuickView(null)} aria-label="Закрыть быстрый просмотр"><X /></button><button className="nm-quick-image-zoom" onClick={() => setLightbox({ src: quickView.image, alt: `${quickView.quickTitle} product`, title: quickView.quickTitle, images: (quickView.gallery ?? [quickView.image]).map((src) => ({ src, alt: `${quickView.quickTitle} product`, title: quickView.quickTitle })) })} aria-label={`Увеличить изображение ${quickView.quickTitle}`}><ProgressiveImage src={quickView.image} alt={`${quickView.quickTitle} product`} /><ZoomIn size={18} /></button><div><p className="nm-eyebrow">Быстрый просмотр / {quickView.products}</p><h2>{quickView.quickTitle}</h2><p>{quickView.quickCopy}</p><strong>{quickView.price.toLocaleString("ru-RU")} ₽</strong><div className="nm-quick-actions"><button className="nm-cta" onClick={() => addToLocalCart(quickView)}>Добавить в корзину <ArrowDownRight size={17} /></button><button className={`nm-quick-secondary ${favoriteIds.includes(favoriteProductId(quickView.quickTitle)) ? "is-saved" : ""}`} onClick={() => toggleFavorite(quickView)} aria-pressed={favoriteIds.includes(favoriteProductId(quickView.quickTitle))}><Heart size={15} fill={favoriteIds.includes(favoriteProductId(quickView.quickTitle)) ? "currentColor" : "none"} /> {favoriteIds.includes(favoriteProductId(quickView.quickTitle)) ? "В избранном" : "В избранное"}</button><button className={`nm-quick-secondary ${saved.includes(quickView.number) ? "is-saved" : ""}`} onClick={() => saveLook(quickView)}><Heart size={15} /> {saved.includes(quickView.number) ? "Образ сохранён" : "Сохранить образ"}</button><button className="nm-quick-secondary" onClick={() => shareLook(quickView)}><Share2 size={15} /> Поделиться</button></div><Link className="nm-underlink nm-quick-open" href={`/product/${quickView.quickTitle.toLowerCase().replaceAll(" ", "-")}`}>Открыть страницу товара <ArrowUpRight size={15} /></Link></div></aside></div>}{lightbox && <Lightbox src={lightbox.src} alt={lightbox.alt} title={lightbox.title} images={lightbox.images} onClose={() => setLightbox(null)} />}</div>;
}
