import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowLeft, ArrowUpRight, Eye, Heart, Share2, X } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";

// Style reminder: Lookbook extends Occult Luxury Editorial with asymmetric spreads,
// archival captions, orange commerce signals, and fast object discovery in-place.
const assets = { hero: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663894363217/XgTNBfpPRvrnTFPr.jpg", category: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663894363217/lCrSqnLAXFKXmWXd.jpg", raven: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663894363217/RCOUOqqGlNukXVjv.jpg", nocturne: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663894363217/lJJsOdgSMDOjJmdQ.jpg", mark: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663894363217/FcXuAAsdOxmisWCl.png" };
type Look = { number: string; title: string; note: string; image: string; products: string; quickTitle: string; quickCopy: string; price: number };
const looks: Look[] = [
  { number: "01", title: "The threshold", note: "A silhouette for rooms that keep their own hours.", image: assets.raven, products: "Raven Hour / Acid Moon", quickTitle: "Raven Hour", quickCopy: "Heavy matte cotton, hidden satin lining, and an architectural hood.", price: 8800 },
  { number: "02", title: "Low flame", note: "Objects that make the air feel considered.", image: assets.category, products: "Black Fig / Ember Ritual", quickTitle: "Black Fig", quickCopy: "A low flame with a fruit-dark finish: fig, clove leaf and wet stone.", price: 2400 },
  { number: "03", title: "A quiet witness", note: "Leave one beautiful thing where it can watch.", image: assets.nocturne, products: "Nocturne / The Last Séance", quickTitle: "Nocturne", quickCopy: "Hand-finished black ceramic with a soft cotton tie and a quiet point of view.", price: 5600 },
];
const addToLocalCart = (look: Look) => { const product = { id: look.quickTitle.toLowerCase().replaceAll(" ", "-"), title: look.quickTitle, slug: look.quickTitle.toLowerCase().replaceAll(" ", "-"), category: "Lookbook", price: look.price, shortDescription: look.quickCopy, description: look.quickCopy, tags: ["lookbook"], image: look.image, colors: ["#17151b"], stock: 8, featured: false, badge: "lookbook" }; let current: Array<{ product: typeof product; quantity: number }> = []; try { current = JSON.parse(localStorage.getItem("night-market-cart") || "[]"); } catch { current = []; } const exists = current.find((line) => line.product.id === product.id); localStorage.setItem("night-market-cart", JSON.stringify(exists ? current.map((line) => line.product.id === product.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { product, quantity: 1 }])); toast.success(`${look.quickTitle} добавлен в корзину`, { description: "Можно продолжить смотреть Lookbook." }); };

export default function Lookbook() {
  const [quickView, setQuickView] = useState<Look | null>(null);
  const [saved, setSaved] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("night-market-lookbook-saved") || "[]"); } catch { return []; } });
  useEffect(() => { const shared = new URLSearchParams(window.location.search).get("look"); const match = shared ? looks.find((look) => look.number === shared) : undefined; if (match) setQuickView(match); const onEscape = (event: KeyboardEvent) => { if (event.key === "Escape") setQuickView(null); }; window.addEventListener("keydown", onEscape); return () => window.removeEventListener("keydown", onEscape); }, []);
  const saveLook = (look: Look) => { const next = saved.includes(look.number) ? saved.filter((id) => id !== look.number) : [...saved, look.number]; setSaved(next); localStorage.setItem("night-market-lookbook-saved", JSON.stringify(next)); toast.success(next.includes(look.number) ? "Образ сохранён" : "Образ удалён из избранного"); };
  const shareLook = async (look: Look) => { const url = `${window.location.origin}/lookbook?look=${look.number}`; try { if (navigator.share) await navigator.share({ title: `NIGHT MARKET — ${look.title}`, text: look.note, url }); else { await navigator.clipboard.writeText(url); toast.success("Ссылка скопирована", { description: url }); } } catch { await navigator.clipboard?.writeText(url); toast.success("Ссылка скопирована", { description: url }); } };
  return <div className="nm-site nm-lookbook"><header className="nm-header"><Link className="nm-brand" href="/" aria-label="NIGHT MARKET home"><img src={assets.mark} alt="" /><span>NIGHT<br /><em>MARKET</em></span></Link><nav className="nm-nav" aria-label="Primary navigation"><Link href="/">Catalog</Link><a href="#looks">Collections</a><a href="#editorial-note">About</a></nav><Link className="nm-text-button" href="/">← Back to market</Link></header><main>
    <section className="nm-look-hero"><div><p className="nm-kicker"><span className="nm-dot" /> Lookbook / issue 04</p><h1>Make the<br /><i>room</i> strange.</h1><p className="nm-hero-lede">Three arrangements for the hours after the obvious. Objects, texture and silhouette in a quieter register.</p><a className="nm-cta" href="#looks">Enter the lookbook <ArrowDownRight size={18} /></a></div><div className="nm-look-hero-image"><img src={assets.hero} alt="A glowing obsidian talisman in a dark editorial setting" /><span>NM / 04<br /><b>FIELD NOTES</b></span></div></section>
    <section id="looks" className="nm-look-list">{looks.map((look, index) => <article className={`nm-look ${index % 2 ? "nm-look-reverse" : ""}`} key={look.number}><div className="nm-look-image"><img src={look.image} alt={`${look.title} editorial arrangement`} /><span>{look.number} / 03</span><button className="nm-look-quick" onFocus={() => setQuickView(look)} onClick={() => setQuickView(look)} aria-label={`Quick view ${look.quickTitle}`}><Eye size={15} /> Quick view</button></div><div className="nm-look-copy"><p className="nm-eyebrow">{look.products}</p><h2>{look.title}</h2><p>{look.note}</p><button className="nm-underlink" onClick={() => setQuickView(look)}>Quick view <Eye size={15} /></button></div></article>)}</section>
    <section id="editorial-note" className="nm-look-note"><img src={assets.mark} alt="" /><div><p className="nm-eyebrow">A note from the archive</p><h2>Good atmosphere<br /><i>is useful.</i></h2><p>We build each look around one anchor object, then let texture and shadow do the rest. Nothing here is filler. If it changes the room, it belongs.</p><Link className="nm-underlink" href="/">Return to the market <ArrowLeft size={15} /></Link></div></section>
  </main><footer className="nm-footer"><Link className="nm-brand" href="/"><img src={assets.mark} alt="" /><span>NIGHT<br /><em>MARKET</em></span></Link><p>Objects for after dark.</p><div><Link href="/">Catalog</Link><a href="#looks">Lookbook</a><a href="mailto:hello@nightmarket.example">Contact</a></div><small>© 2026 NIGHT MARKET.</small></footer><div className="nm-noise" aria-hidden="true" />{quickView && <div className="nm-quick-overlay" onClick={() => setQuickView(null)}><aside className="nm-quick-view" onClick={(event) => event.stopPropagation()} role="dialog" aria-modal="true" aria-label={`Quick view ${quickView.quickTitle}`}><button className="nm-close" onClick={() => setQuickView(null)} aria-label="Close quick view"><X /></button><img src={quickView.image} alt={`${quickView.quickTitle} product`} /><div><p className="nm-eyebrow">Quick view / {quickView.products}</p><h2>{quickView.quickTitle}</h2><p>{quickView.quickCopy}</p><strong>{quickView.price.toLocaleString("ru-RU")} ₽</strong><div className="nm-quick-actions"><button className="nm-cta" onClick={() => addToLocalCart(quickView)}>Add to bag <ArrowDownRight size={17} /></button><button className={`nm-quick-secondary ${saved.includes(quickView.number) ? "is-saved" : ""}`} onClick={() => saveLook(quickView)}><Heart size={15} /> {saved.includes(quickView.number) ? "Saved" : "Save look"}</button><button className="nm-quick-secondary" onClick={() => shareLook(quickView)}><Share2 size={15} /> Share</button></div><Link className="nm-underlink nm-quick-open" href="/">Open full object <ArrowUpRight size={15} /></Link></div></aside></div>}</div>;
}
