import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { Link } from "wouter";

const sections = [
  { id: "delivery", title: "Доставка", body: "Доставка доступна по России. Тариф рассчитывается по выбранной зоне: Москва и область, Центральный округ, Северо-Запад, Юг России, Поволжье, Урал, Сибирь и Дальний Восток. Бесплатная доставка применяется от 10 000 ₽. Финальный срок и стоимость должны быть подтверждены оператором до оплаты." },
  { id: "returns", title: "Заказ и оплата", body: "Сайт не принимает онлайн-оплату. После нажатия «Оформить заказ в Telegram» откроется переписка с @eloquncy и готовым составом заказа. Наличие, адрес, финальная доставка и способ оплаты подтверждаются лично оператором в Telegram до оформления." },
  { id: "privacy", title: "Конфиденциальность", body: "Витрина хранит локальные настройки корзины, региона и избранного в браузере. Реальные персональные данные и платёжная информация не собираются демо-режимом. Подключение аналитики и провайдеров должно проходить с отдельной политикой обработки данных." },
  { id: "support", title: "Поддержка", body: "По вопросам ассортимента и заказа напишите в Telegram: @eloquncy. Сайт передаёт в переписку только выбранные товары, суммы, регион и срок доставки; платёжные данные на сайте не вводятся и не сохраняются." },
];

export default function Policies() {
  return <div className="nm-site"><div className="nm-noise" aria-hidden="true" /><header className="nm-header"><Link className="nm-brand" href="/" aria-label="NIGHT MARKET home"><span>NIGHT<br /><em>MARKET</em></span></Link><nav className="nm-nav" aria-label="Primary navigation"><Link href="/">Catalog</Link><Link href="/lookbook">Lookbook</Link><Link href="/favorites">Favorites</Link></nav><Link className="nm-text-button" href="/">← Back to market</Link></header><main className="nm-policy-page" id="top"><p className="nm-eyebrow">NIGHT MARKET / CONDITIONS</p><h1>Before the<br /><i>night begins.</i></h1><p className="nm-policy-lede">Прозрачные условия для витрины NIGHT MARKET. Вы выбираете товары здесь, а подтверждение наличия, адреса и оплаты продолжаете лично в Telegram.</p><div className="nm-policy-grid">{sections.map((section) => <section key={section.id} id={section.id}><p className="nm-eyebrow">0{sections.indexOf(section) + 1} / {section.id}</p><h2>{section.title}</h2><p>{section.body}</p></section>)}</div><Link className="nm-underlink" href="/"><ArrowLeft size={15} /> Return to the market</Link></main><footer className="nm-footer"><span>© 2026 NIGHT MARKET.</span><a href="https://t.me/eloquncy" target="_blank" rel="noreferrer">Telegram @eloquncy <ArrowUpRight size={14} /></a></footer></div>;
}
