export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  nlpApiUrl: process.env.NLP_API_BASE_URL ?? "",
  nlpApiKey: process.env.NLP_API_KEY ?? "",
  reviewsProvider: process.env.REVIEWS_PROVIDER ?? "",
  reviewsApiUrl: process.env.REVIEWS_API_BASE_URL ?? "",
  reviewsApiToken: process.env.REVIEWS_API_TOKEN ?? "",
  reviewsStoreDomain: process.env.REVIEWS_STORE_DOMAIN ?? "",
  freeShippingThreshold: Number(process.env.FREE_SHIPPING_THRESHOLD ?? 10000),
};
